CREATE INDEX poe_order_o4 ON "MIMIC2"."mimic.tables::poe_order" ("icustay_id");
CREATE INDEX poe_order_o1 ON "MIMIC2"."mimic.tables::poe_order" ("subject_id","hadm_id");
CREATE INDEX poe_order_o3 ON "MIMIC2"."mimic.tables::poe_order" ("hadm_id");
CREATE INDEX poe_order_o2 ON "MIMIC2"."mimic.tables::poe_order" ("subject_id");
CREATE INDEX a_meddurations_o1 ON "MIMIC2"."mimic.tables::a_meddurations" ("cuid");
CREATE UNIQUE INDEX a_meddurations_pk ON "MIMIC2"."mimic.tables::a_meddurations" ("subject_id","itemid","elemid","starttime");
CREATE INDEX a_meddurations_o4 ON "MIMIC2"."mimic.tables::a_meddurations" ("icustay_id");
CREATE INDEX a_meddurations_o2 ON "MIMIC2"."mimic.tables::a_meddurations" ("subject_id");
CREATE INDEX a_meddurations_o3 ON "MIMIC2"."mimic.tables::a_meddurations" ("itemid");
CREATE INDEX additives_o6 ON "MIMIC2"."mimic.tables::additives" ("cgid");
CREATE INDEX additives_o4 ON "MIMIC2"."mimic.tables::additives" ("itemid");
CREATE INDEX additives_o2 ON "MIMIC2"."mimic.tables::additives" ("subject_id");
CREATE INDEX additives_o1 ON "MIMIC2"."mimic.tables::additives" ("cuid");
CREATE INDEX additives_o5 ON "MIMIC2"."mimic.tables::additives" ("icustay_id");
CREATE INDEX additives_o3 ON "MIMIC2"."mimic.tables::additives" ("ioitemid");
CREATE INDEX poe_med_o1 ON "MIMIC2"."mimic.tables::poe_med" ("poe_id");
CREATE INDEX totalbalevents_o3 ON "MIMIC2"."mimic.tables::totalbalevents" ("itemid");
CREATE INDEX totalbalevents_o5 ON "MIMIC2"."mimic.tables::totalbalevents" ("cgid");
CREATE INDEX totalbalevents_o1 ON "MIMIC2"."mimic.tables::totalbalevents" ("cuid");
CREATE INDEX totalbalevents_o4 ON "MIMIC2"."mimic.tables::totalbalevents" ("icustay_id");
CREATE INDEX totalbalevents_o2 ON "MIMIC2"."mimic.tables::totalbalevents" ("subject_id");
CREATE INDEX a_iodurations_o1 ON "MIMIC2"."mimic.tables::a_iodurations" ("cuid");
CREATE INDEX a_iodurations_o2 ON "MIMIC2"."mimic.tables::a_iodurations" ("subject_id");
CREATE UNIQUE INDEX a_iodurations_pk ON "MIMIC2"."mimic.tables::a_iodurations" ("subject_id","itemid","elemid","starttime");
CREATE INDEX a_iodurations_o3 ON "MIMIC2"."mimic.tables::a_iodurations" ("itemid");
CREATE INDEX noteevents_o6 ON "MIMIC2"."mimic.tables::noteevents" ("cgid");
CREATE INDEX noteevents_o1 ON "MIMIC2"."mimic.tables::noteevents" ("cuid");
CREATE INDEX noteevents_o4 ON "MIMIC2"."mimic.tables::noteevents" ("hadm_id");
CREATE INDEX noteevents_o2 ON "MIMIC2"."mimic.tables::noteevents" ("subject_id");
CREATE INDEX noteevents_o5 ON "MIMIC2"."mimic.tables::noteevents" ("category");
CREATE INDEX noteevents_o3 ON "MIMIC2"."mimic.tables::noteevents" ("icustay_id");
CREATE INDEX ioevents_o6 ON "MIMIC2"."mimic.tables::ioevents" ("cgid");
CREATE INDEX labevents_o4 ON "MIMIC2"."mimic.tables::labevents" ("itemid");
CREATE INDEX labevents_o2 ON "MIMIC2"."mimic.tables::labevents" ("hadm_id");
CREATE INDEX labevents_o1 ON "MIMIC2"."mimic.tables::labevents" ("subject_id");
CREATE INDEX labevents_o3 ON "MIMIC2"."mimic.tables::labevents" ("icustay_id");
CREATE INDEX labevents_o5 ON "MIMIC2"."mimic.tables::labevents" ("icustay_id","itemid");
CREATE INDEX chartevents_o4 ON "MIMIC2"."mimic.tables::chartevents" ("itemid");
CREATE INDEX chartevents_o2 ON "MIMIC2"."mimic.tables::chartevents" ("subject_id","itemid");
CREATE INDEX chartevents_o5 ON "MIMIC2"."mimic.tables::chartevents" ("icustay_id");
CREATE INDEX chartevents_o1 ON "MIMIC2"."mimic.tables::chartevents" ("cuid");
CREATE INDEX chartevents_o3 ON "MIMIC2"."mimic.tables::chartevents" ("subject_id");
CREATE INDEX chartevents_o6 ON "MIMIC2"."mimic.tables::chartevents" ("charttime");
CREATE INDEX chartevents_o7 ON "MIMIC2"."mimic.tables::chartevents" ("cgid");
CREATE INDEX procedureevents_o2 ON "MIMIC2"."mimic.tables::procedureevents" ("itemid");
CREATE INDEX procedureevents_o1 ON "MIMIC2"."mimic.tables::procedureevents" ("hadm_id");
CREATE INDEX comorbidity_o3 ON "MIMIC2"."mimic.tables::comorbidity_scores" ("subject_id","hadm_id");
CREATE INDEX comorbidity_o2 ON "MIMIC2"."mimic.tables::comorbidity_scores" ("hadm_id");
CREATE INDEX comorbidity_o1 ON "MIMIC2"."mimic.tables::comorbidity_scores" ("subject_id");
CREATE INDEX admissions_o1 ON "MIMIC2"."mimic.tables::admissions" ("subject_id");
CREATE INDEX demographicevents_o1 ON "MIMIC2"."mimic.tables::demographicevents" ("hadm_id");
CREATE INDEX demographicevents_o2 ON "MIMIC2"."mimic.tables::demographicevents" ("itemid");
CREATE UNIQUE INDEX icustay_detail_pk ON "MIMIC2"."mimic.tables::icustay_detail" ("icustay_id");
CREATE UNIQUE INDEX icustay_detail_u1 ON "MIMIC2"."mimic.tables::icustay_detail" ("subject_id","icustay_id");
CREATE INDEX a_chartdurations_o3 ON "MIMIC2"."mimic.tables::a_chartdurations" ("icustay_id");
CREATE INDEX a_chartdurations_o1 ON "MIMIC2"."mimic.tables::a_chartdurations" ("cuid");
CREATE INDEX a_chartdurations_o4 ON "MIMIC2"."mimic.tables::a_chartdurations" ("itemid");
CREATE INDEX a_chartdurations_o2 ON "MIMIC2"."mimic.tables::a_chartdurations" ("subject_id");
CREATE UNIQUE INDEX d_chartitems_detail_u1 ON "MIMIC2"."mimic.tables::d_chartitems_detail" ("itemid");
CREATE UNIQUE INDEX d_chartitems_detail_u2 ON "MIMIC2"."mimic.tables::d_chartitems_detail" ("itemid","label","label_lower","category");
CREATE INDEX d_chartitems_detail_o1 ON "MIMIC2"."mimic.tables::d_chartitems_detail" ("label_lower");
CREATE INDEX drgevents_o2 ON "MIMIC2"."mimic.tables::drgevents" ("itemid");
CREATE INDEX drgevents_o1 ON "MIMIC2"."mimic.tables::drgevents" ("hadm_id");
CREATE INDEX drgevents_o32 ON "MIMIC2"."mimic.tables::drgevents" ("subject_id");
CREATE UNIQUE INDEX icustayev_u1 ON "MIMIC2"."mimic.tables::icustayevents" ("subject_id","intime");
CREATE INDEX icustayevents_o4 ON "MIMIC2"."mimic.tables::icustayevents" ("first_careunit");
CREATE INDEX icustayevents_o3 ON "MIMIC2"."mimic.tables::icustayevents" ("last_careunit");
CREATE INDEX icustayevents_o1 ON "MIMIC2"."mimic.tables::icustayevents" ("intime");
CREATE INDEX icustayevents_o2 ON "MIMIC2"."mimic.tables::icustayevents" ("outtime");
CREATE INDEX icd9_o2 ON "MIMIC2"."mimic.tables::icd9" ("hadm_id");
CREATE INDEX icu9_o1 ON "MIMIC2"."mimic.tables::icd9" ("subject_id");
CREATE INDEX censusevents_o4 ON "MIMIC2"."mimic.tables::censusevents" ("careunit");
CREATE INDEX censusevents_01 ON "MIMIC2"."mimic.tables::censusevents" ("destcareunit");
CREATE INDEX censusevents_u1 ON "MIMIC2"."mimic.tables::censusevents" ("subject_id","intime");
CREATE INDEX censusevents_o3 ON "MIMIC2"."mimic.tables::censusevents" ("icustay_id");
CREATE INDEX censusevents_o2 ON "MIMIC2"."mimic.tables::censusevents" ("subject_id");
CREATE INDEX microbiologyevents_o3 ON "MIMIC2"."mimic.tables::microbiologyevents" ("subject_id");
CREATE INDEX microbiologyevents_o1 ON "MIMIC2"."mimic.tables::microbiologyevents" ("ab_itemid");
CREATE INDEX microbiologyevents_o4 ON "MIMIC2"."mimic.tables::microbiologyevents" ("org_itemid");
CREATE INDEX microbiologyevents_o5 ON "MIMIC2"."mimic.tables::microbiologyevents" ("spec_itemid");
CREATE INDEX microbiologyevents_o2 ON "MIMIC2"."mimic.tables::microbiologyevents" ("hadm_id");
CREATE INDEX icustay_days_o1 ON "MIMIC2"."mimic.tables::icustay_days" ("icustay_id","seq");
CREATE INDEX medevents_o3 ON "MIMIC2"."mimic.tables::medevents" ("itemid");
CREATE INDEX medevents_o5 ON "MIMIC2"."mimic.tables::medevents" ("icustay_id");
CREATE INDEX medevents_o2 ON "MIMIC2"."mimic.tables::medevents" ("subject_id");
CREATE UNIQUE INDEX medevents_pk ON "MIMIC2"."mimic.tables::medevents" ("subject_id","itemid","charttime","elemid");
CREATE INDEX medevents_o6 ON "MIMIC2"."mimic.tables::medevents" ("cgid");
CREATE INDEX medevents_o4 ON "MIMIC2"."mimic.tables::medevents" ("solutionid");
CREATE INDEX medevents_o1 ON "MIMIC2"."mimic.tables::medevents" ("cuid");
CREATE INDEX deliveries_o1 ON "MIMIC2"."mimic.tables::deliveries" ("cuid");
CREATE INDEX deliveries_o3 ON "MIMIC2"."mimic.tables::deliveries" ("ioitemid");
CREATE INDEX deliveries_o5 ON "MIMIC2"."mimic.tables::deliveries" ("cgid");
CREATE INDEX deliveries_o4 ON "MIMIC2"."mimic.tables::deliveries" ("icustay_id");
CREATE UNIQUE INDEX deliveries_pk ON "MIMIC2"."mimic.tables::deliveries" ("subject_id","ioitemid","charttime","elemid");
CREATE INDEX deliveries_o2 ON "MIMIC2"."mimic.tables::deliveries" ("subject_id");
